#!/bin/sh
src=cmd/fibonacci/main.go
name=fibonacci
files="LICENSE README.md"
main() {
  mkdir out
  archive_binaries && produce_checksums
}
archive_binaries() {
  atail="tar.gz"
  atool="tar czf"
  for os in openbsd freebsd netbsd dragonfly linux darwin windows; do
    GOOS=$os
    for arch in amd64 386; do
      GOARCH=$arch
      export GOOS GOARCH
      case $os in
        dragonfly|darwin) test "$arch" = "amd64" || continue ;;
        windows) atail="zip"; atool="zip -q"; ext=".exe" ;;
      esac
      CGO_ENABLED=0 go build -o $name$ext -ldflags="-s -w" $src
      $atool out/$name-$os-$arch.$atail $name$ext $files
    done
  done
}
produce_checksums() {
  cd out || return
  for archive in *; do
    shasum -a 256 "$archive" >> CHECKSUMS
  done
}
main "$@"
