name: CD
on:
  push:
    tags:
      - "v*.*.*"

env:
  CMDPATH: ./cmd/fibonacci

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v3.2.1
        with:
          go-version: 1.19

      - name: Release
        runs-on: ubuntu-latest
        strategy:
          matrix:
            goos: [openbsd, freebsd, netbsd, dragonfly, linux, darwin, windows]
            goarch: ["386", "amd64"]
            exclude:
              # do not build for architectures Go compiler does not
              # support; run `go tool dist list` for more information
              - goarch: "386"
                goos: dragonfly
              - goarch: "386"
                goos: darwin
        steps:
          - uses: actions/checkout@v3
          - uses: wangyoucao577/go-release-action@v1.30
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              goos: ${{ matrix.goos }}
              goarch: ${{ matrix.goarch }}
              project_path: ${{ env.CMDPATH }}
              ldflags: "-s -w"
