name: CD
on:
  push:
    tags:
      - "v*.*.*"

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v3.2.1
        with:
          go-version: 1.19

      - name: Build
        run: misc/build
